# Site
title: Silo
subtitle: arte e latitude rural

# URL
url: http://silo.org.br
baseurl: '/silo-cover-test'
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 5666
future: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "home"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "home"

# Data
social:
  facebook: "https://www.facebook.com/silo.arte.latitude.rural"
  instagram: "https://www.instagram.com/silo.arte.e.latitude.rural"
  github: "https://github.com/associacaosilo"
  twitter: "https://twitter.com/SiloLatitude"
  envelope-o: "mailto:contato@silo.org.br"
twitter_user: "SiloLatitude"
