# Site
title: Silo
subtitle: arte e latitude rural

# URL
url: http://silo.org.br
baseurl: '/silo-test'
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 5666
future: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"

# Data
social:
  facebook: "https://www.facebook.com/silo.arte.latitude.rural"
  instagram: "https://www.instagram.com/silo.arte.e.latitude.rural"
  github: "https://github.com/associacaosilo"
  twitter: "https://twitter.com/SiloLatitude"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:contato@silo.org.br"
twitter_user: "SiloLatitude"

# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _pages/404.md
    - _pages/noticias.md
    - _pages/quem-somos.md
    - _pages/projects
    - _sass
    - css
    - js
    - CNAME
    - TODO.md
    - media/favicons
    - media/swipebox
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Título do post"
          placeholder: "Colocar Aqui o Nome do Post"
      - name: "cover"
        field:
          element: "text"
          label: "imagem de capa"
          placeholder: "media/images/cover.jpg"
      - name: "category"
        field:
          element: "multiselect"
          label: "categorias do post (usar categoria 'silo' para posts genéricos)"
          placeholder: "clique aqui"
          options:
            - name: 'Silo'
              value: 'silo'
            - name: 'Encontrada'
              value: 'encontrada'
            - name: 'Interactivos!'
              value: 'interactivos'
            - name: 'Residência'
              value: 'residence'
      - name: "lang"
        field:
          element: "select"
          label: "idioma do post"
          placeholder: "clique aqui"
          options:
            - name: 'Português'
              value: 'pt'
            - name: 'English'
              value: 'en'
      - name: "ref"
        field:
          element: "text"
          label: "referência para posts bilíngue (igual em todas as línguas)"
          placeholder: "residencia-convocatoria-2017"
      - name: "swipebox"
        field:
          element: "text"
          label: "prefixo dos arquivos de imagem para serem incluidos na galeria"
          placeholder: "p1_"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
          placeholder: "Colocar Aqui o Nome Da Página"
      - name: "ref"
        field:
          element: "text"
          label: "referência para páginas bilíngue (igual em todas as línguas)"
          placeholder: "pagina-sobre"
      - name: "permalink"
        field:
          element: "text"
          label: "link dessa página"
          placeholder: "/contato/"
      - name: "lang"
        field:
          element: "select"
          label: "idioma do post"
          placeholder: "clique aqui"
          options:
            - name: 'Português'
              value: 'pt'
            - name: 'English'
              value: 'en'
    _pages/people:
      - name: "link"
        field:
          element: "text"
          label: "link pra página da pessoa"
          placeholder: "minhapagina.com.br"
      - name: "cover"
        field:
          element: "text"
          label: "imagem da pessoa"
          placeholder: "media/images/people/pessoa.jpg"
      - name: "ref"
        field:
          element: "text"
          label: "referência para páginas bilíngue (igual em todas as línguas)"
          placeholder: "bio-beringela"
      - name: "category"
        field:
          element: "select"
          label: "sub-grupo organizacional"
          placeholder: "clique aqui"
          options:
            - name: 'Diretoria'
              value: 'diretoria'
            - name: 'Associadas'
              value: 'associadas'
            - name: 'Conselho'
              value: 'conselho'
            - name: 'Equipe'
              value: 'equipe'
      - name: "lang"
        field:
          element: "select"
          label: "idioma do post"
          placeholder: "clique aqui"
          options:
            - name: 'Português'
              value: 'pt'
            - name: 'English'
              value: 'en'
